### ISSUE TITLE
Unable to find Authreducer

### ISSUE THREAD

**Issue by piyushatgeoalgo** [poojan-bacancy/ReduxFormPart2#1]
Unable to find A
![Untitled](https://user-images.githubusercontent.com/83804284/141251248-142e60cb-3800-4c16-830b-25b8a55500d4.png)
uthReducer

**Comment by poojan-bacancy** [comment]
Please put export const combinedReducers part after declaring AuthReducer.
Change 
export const combinedReducers = combineReducers({
    form : formReducer,
    Auth : AuthReducer  // AuthReducers -> AuthReducer
})
